# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc957b553f2cf01569a583a4d7fc57eb32d633b9d1fc71f92d1b9a6d815d18b71fc11e61b2bd2f920036759a93bc69e472a814c1ec5ff8a3c7b0f77490d2ea6c

test:
  secret_key_base: 02928b7700a7196a0d0bc9f74e143cb0fe42c1db717733e033906d27067d40ee7c6905449ae10258c4699798acb804c1e0f8f1a92a8143f43e6d3bf86e834d44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
